title: Sara Mascia
email: sara.mascia@ista.ac.at
description: Personal website of Sara Mascia, astronomer, ISTA Prize Fellow.
baseurl: ""
url: "https://masciasara.github.io"
github_username: masciasara
keywords: "astronomy,reionization,galaxies,jwst,mascia"

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
